import os
import sys

import gradio as gr
from PIL import Image, ImageFilter

# os.path.abspath("..")
sys.path.append(os.path.abspath("."))

from domain.models import load_model, load_processor
from services.predict import predict

processor = load_processor()
model = load_model()


def test_model(image):
    image = Image.fromarray(image)
    predicted_label, predicted_prob = predict(processor, model, image)
    return predicted_label, predicted_prob


def gaussian_blur(image):
    # numpy to pillow image
    image = Image.fromarray(image)
    # apply gaussian blur to pillow image
    blur = image.filter(ImageFilter.GaussianBlur(15))

    return blur


def user_greeting(name):
    return (
        "안녕하세요! "
        + name
        + "님, 첫 번째 Gradio 애플리케이션에 오신 것을 환영합니다!😎"
    )


# app = gr.Interface(fn=user_greeting, inputs="text", outputs="text")
# app = gr.Interface(fn=gaussian_blur, inputs="image", outputs="image")

app = gr.Interface(
    fn=test_model,
    inputs="image",
    outputs=[
        gr.Textbox(label="Predicted Label"),
        gr.Number(label="Predicted Probability"),
    ],
    title="AI vs Human Image Detector",
    description="Upload an image to test if it is generated by AI or not",
)
app.launch()
