name: Lint and Build

on:
  workflow_dispatch:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install isort

      - name: Run lint(black and isort)
        run: |
          black .
          isort .
        continue-on-error: true

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: lint"